name: will.stedden.org

social:
  - name: linkedin
    url: https://www.linkedin.com/in/willstedden
  - name: github
    url: https://github.com/stedn
  - name: codepen
    url: https://codepen.io/stedn/
  - name: reddit-alien
    url: https://www.reddit.com/user/bonkerfield
  - name: mastodon
    url: https://sigmoid.social/@bonkerfield